services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "5000:5000"
    volumes:
      # Mount source code for hot reload
      - ./apps/server/src:/app/apps/server/src
      - ./apps/server/tsconfig.json:/app/apps/server/tsconfig.json
      - ./apps/server/nest-cli.json:/app/apps/server/nest-cli.json
      - ./apps/server/package.json:/app/apps/server/package.json
      - /app/apps/server/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://admin:password123@db:5432/neighborhood_hub
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    image: postgis/postgis
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=neighborhood_hub
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: