services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "5000:5000"
    volumes:
      - ./apps/server/src:/app/apps/server/src
      - /app/apps/server/node_modules
    env_file:
      - ./apps/server/.env
    environment:
      - NODE_ENV=development
    depends_on:
      - db

  db:
    image: postgis/postgis
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=neighborhood_hub

volumes:
  postgres_data: